services:

  application:
    build: ./
    container_name: star-wars-wiki
    ports:
      - '3000:3000'
    volumes:
      - app:/var/lib/project/src
      - node-modules:/var/lib/project/node_modules

volumes:
  app:
  node-modules: